### ISSUE TITLE
Duplicated files with different cases in source code

### ISSUE THREAD

**Issue by Tyrben** [actinoide/Road-of-Avalon-Tracker#5]
This doesn't look to bother Windows, but this is certainly a mistake.
Some files exist in 2 versions only with a case difference:

- albionzonedefinition.cs
- AlbionZoneDefinition.cs
- globalvariables.cs
- GlobalVariables.cs

(This project is interesting. I would like to make it run after the recent updates of the game.)
Could a linux version be possible? (Meaning: Can it compile with Mono or run on Wine?)

**Comment by actinoide** [comment]
the duplicate files were a github side issue. on my end i had renamed them with the proper casing and github assumed they were new files. 
i have no experience with mono or wine so i cant tell you if it can compile with them. if you code yourself you could try it otherwise i could have a look.
ps. sorry for taking this long to respond i havent checked my github in a while.
